#!/bin/bash

listpath="${HOME}/.config/autostart"
if ! test -d "$listpath"; then
	echo "$(basename "$0"): $listpath does not exist" >&2
	exit 1
fi

for file in "$listpath"/*.auto; do
	trunclist="$(grep -o "^\w*" "$file" | tr '\n' ' ')"
	choice=$( echo "yes|no" | \
		rofi -dmenu -no-custom -i -sep '|' \
			-p "Execute $(basename "$file")? ( $trunclist)")
	if test "$choice" != "yes"; then
		continue
	fi
	while IFS= read -r line; do
	  # if comment, ignore
	  if [[ "$line" =~ ^# ]]; then continue; fi
		if pgrep -fx "$line" > /dev/null || pgrep -x "$line" > /dev/null; then
		  echo "$line: already running"
		  continue
		fi
		echo "Starting $line"
		# run the command with the arguments (cannot quote)
		setsid -f $line > /dev/null 2>&1
	done < "$file"
done
