#!/bin/bash
if [ -r "$HOME/.config/bar" ]; then
	commands="$(cat ~/.config/bar)"
else commands="date"
fi
left=" "
right=""
while IFS="" read -r com || [ -n "$com" ]
do
	co="$(timeout 0.5s $com || echo "⚠️")"
	if [ "$co" == "" ]; then continue; fi
	output="${output}${left}${co}${right}"
done < <(echo "$commands"|grep -v '^#')
echo "$output" | tr -d '\n'
echo
