#!/bin/bash
if [ -r $HOME/.config/bar ]; then
	commands=$(cat ~/.config/bar)
else commands="date"
fi
left=" [ "
right=" ] "
for com in $commands
do
	output="$output$left$($com)$right"
done
echo "$output" | tr -d '\n'
echo
