#!/bin/bash
if [ -r "$HOME/.config/bar" ]; then
	commands=$(cat ~/.config/bar)
else commands="date"
fi
left="["
right="]"
for com in $commands
do
	co="$($com)"
	if [ "$co" == "" ]; then continue; fi
	output="$output$left$co$right"
done
echo "$output" | tr -d '\n'
echo
