#!/bin/bash
ring(){
	sine 500 0.1
	sine 300 0.1
	sine 250 0.1
}
while true; do
	capacity=$(cat /sys/class/power_supply/BAT*/capacity )
	status=$(cat /sys/class/power_supply/BAT*/status )
	if [ "$status" != "Discharging" ]; then
		sleep 1
		continue
	fi
	if [[ $capacity -lt 10 ]] ; then 
		ring
		sleep $capacity
	fi
done
