#!/usr/bin/env bash
ring(){
	sine 500 0.1
	sine 300 0.1
	sine 250 0.1
}
while true; do
	capacity=$(cat /sys/class/power_supply/BAT*/capacity )
	status=$(cat /sys/class/power_supply/BAT*/status )
	sleep 1
	if [ "$status" != "Discharging" ]; then
		continue
	fi
	if [[ $capacity -lt 15 ]] ; then 
		ring
		sleep "$capacity"
	fi
done
