#!/usr/bin/env bash
for bat in /sys/class/power_supply/BAT*; do
	level=$(cat "$bat"/capacity)
	status=$(cat "$bat"/status)
	if [ "$status" == "Charging" ]; then
		echo " $level%"
		continue
	fi
	case $level in
		?) echo -n "  ";;
		1?) echo -n " ";;
		[23]?) echo -n " ";;
		[456]?) echo -n " ";;
		[78]?) echo -n " ";;
		[9]?|???) echo -n " ";;
		*) echo -n "";;
	esac
	echo "$level%"
done
