#!/usr/bin/env bash
f="$1"
shift
f=${f%.c} # remove .c from filename if it exists
CFLAGS=(-Wall -Werror -O3 -std=c17 -g -lm -pedantic)
echo "$(colr pink)gcc $f.c -o $f ${CFLAGS[*]} && (./$f $* ; rm $f)$(colr default)"
gcc "$f.c" -o "$f" "${CFLAGS[@]}" && (./"$f" "$@" ; rm "$f")
