#!/bin/bash
f="$1"
shift
f=${f%.c} # remove .c from filename if it exists
echo "$(colr pink)gcc $f.c -o $f -lm && (./$f $* ; rm ./$f)$(colr default)"
gcc "$f.c" -o "$f" -lm && (./"$f" "$@" ; rm "./$f")
