#!/usr/bin/env python3
import sys
colors = {
     "default" : "\033[0m",
     "black" : "\033[0;30m",
     "red" : "\033[0;31m",
     "green" : "\033[0;32m",
     "yellow" : "\033[0;33m",
     "blue" : "\033[0;34m",
     "magenta" : "\033[0;35m",
     "pink" : "\033[0;35m",
     "cyan" : "\033[0;36m",
     "white" : "\033[0;37m" 
}
if(len(sys.argv) != 2 or sys.argv[1].lower() not in colors):
	sys.exit(1)
print(colors[sys.argv[1].lower()])
