#!/bin/env python
import sys
colors = {
     "default" : "\033[39m",
     "black" : "\033[30m",
     "red" : "\033[31m",
     "green" : "\033[32m",
     "yellow" : "\033[33m",
     "blue" : "\033[34m",
     "magenta" : "\033[35m",
     "pink" : "\033[35m",
     "cyan" : "\033[36m",
     "white" : "\033[37m" 
}
if(len(sys.argv) != 2 or sys.argv[1].lower() not in colors):
	sys.exit(1)
print(colors[sys.argv[1].lower()])
