#!/bin/env python
import sys
import os
filename = sys.argv[1]
if filename.endswith(".cpp"):
    filename = filename[0:-4]
exec = "g++ " + filename + ".cpp -o " + filename + " && ./" + filename
os.system(f"echo -e \"$(colr pink){exec}$(colr default)\"")
os.system(exec)
