#!/bin/bash
temp=$(sensors | grep -Pio "^(tctl|cpu):.+\+\K\d+")
case $temp in
	[0123]?|?) emo="";;
	4?) emo="";;
	5?) emo="";;
	6?) emo="";;
	[78]?) emo="";;
	*) emo="🌡";;
esac
if [[ $temp -gt 70 || "$1" == "-v" || "$1" == "--verbose" ]]; then
	echo "$emo $temp°C"
else
	echo "$emo"
fi

