#!/bin/bash

# lowers screen brightness, then waits to be killed
# and restores previous brightness on exit.

min_brightness=0
fade_time=200
fade_steps=20

###############################################################################

cb=$(xbacklight -get)
trap 'exit 0' TERM INT
trap 'xbacklight -set $cb' EXIT
xbacklight -time $fade_time -steps $fade_steps -set $min_brightness
sleep inf
