#!/usr/bin/env bash

#prints the dominant color in supplied image in hexadecimal code. #xxxxxx

src=$1
error(){
	echo "$@"
	exit 1
}
if test -z "$1"; then error "usage $(basename "$0") imagefile" ; fi
if test ! -r "$src"; then error "File $src does not exist or is unreadable" ; fi
if test -d "$src"; then error "$src is a directory, not an image" ; fi
if ! isimage "$src"; then error "$src is not a valid image file" ; fi

colors=$( convert "$src" -scale 50x50! -depth 8 +dither -colors 8 -format "%c" histogram:info: | sed -n 's/^[ ]*\(.*\):.*[#]\([0-9a-fA-F]*\) .*$/\1,#\2/p' | sort -r -n -k 1 -t "," | cut -d, -f2 | cut -c1-7 )
echo -e "dominant colors:\n$colors" >&2 # comment out this line to suppress debug info

echo -n "$colors" | head -n 3 | shuf | head -n 1
