#!/usr/bin/env bash

# usage faster <src video> <dest video> <speedup>

# speedup is a floating point number, e.g. 2.0 for double speed

if [ $# -ne 3 ]; then
    echo "Usage: $0 <src video> <dest video> <speedup>"
    exit 1
fi

ffmpeg -i "$1" -filter_complex "[0:v]setpts=PTS/$3[v];[0:a]atempo=$3[a]" -map "[v]" -map "[a]" -c:v libx264 -c:a aac -strict experimental "$2"
