#!/bin/bash

usage(){
  echo " usage: $(basename "$0") name... "
}

if [[ -z "$1" ]] ; then
  usage
  exit
fi

for name in "$@"; do
  output="$(curl -s "https://api.genderize.io/?name=${name}")"
  gender="$(jq -r .gender <<<"$output")"
  probability="$(jq -r .probability <<<"$output")"
  echo "$name: $gender ($probability)"
done


