#!/bin/bash
# takes image input, puts clock in the center and renders output.
if [ -z "$1" ]; then 
	echo "usage: 
	$(basename "$0") src [dest]"
	exit
fi
if [ ! -r "$1" ]; then
	echo "$1 not found"
	exit 1
fi
src="$1"
dest="${2:-output.jpg}"
convert \
	"$src" \
	-geometry 1920:1080 \
	-fill "#00000066" \
	-draw "roundrectangle 720,990 1200,1080 5,5" \
	-gravity center \
	-pointsize 50 \
	-fill "#ffffffaa" \
	-annotate +0+505 "$(clock)" \
	"$dest"
