#!/bin/bash
# takes image input, puts clock in the center and renders output.
if [ -z "$1" ]; then 
	echo "usage: 
	$(basename "$0") src [dest]"
	exit
fi
if [ ! -r "$1" ]; then
	echo "$1 not found"
	exit 1
fi
src="$1"
dest="${2:-output.jpg}"

configpath="$HOME/.config/imgclock"

if [ -x "$configpath" ] ; then 
  "$configpath" "$src" "$dest" ;
  echo "Using $configpath"
else 
  echo "Using defaults"
  convert "$src" \
	-gravity North \
	-pointsize 100 \
	-fill "#ffffff88" \
	-annotate +0+155 "$(clock)" \
  "$dest"
fi
