#!/bin/bash
case $2 in
	here) path="$1";;
	*) path="${HOME}/scripts/$1";;
esac
if [ ! -e "$path" ]
then
	cp "${HOME}/scripts/generic" "$path"
fi
if [ "$EDITOR" = "" ]; then EDITOR=vim; fi
"$EDITOR" "$path"
