#!/usr/bin/env bash
if [ -z "$1" ]; then 
	echo "argument required"
	exit 1
fi
f=${1%.java} # remove .java from filename if it exists
if [ ! -e "$f.java" ]
then
	cp ~/docs/code/boilerplate/template.java "$f.java"
fi
"$EDITOR" "$f.java"
