#!/bin/bash
betterlockscreen -l dimblur
#source $HOME/.config/betterlockscreenrc
#i3lock \
#	-t -i "/home/sayan/pics/Wallpapers/pinksky.jpg" -e \
#	--timepos='x+960:h-70' \
#	--datepos='x+960:h-35' \
#	--timesize=48 --datesize=24 \
#	--insidecolor=$insidecolor --ringcolor=$ringcolor --line-uses-inside \
#	--keyhlcolor=$keyhlcolor --bshlcolor=$bshlcolor --separatorcolor=$separatorcolor \
#	--insidevercolor=$insidevercolor --insidewrongcolor=$insidewrongcolor \
#	--ringvercolor=$ringvercolor --ringwrongcolor=$ringwrongcolor \
#	--radius=100 --ring-width=20 --veriftext='...' --wrongtext='' \
#	--verifcolor="$verifcolor" --timecolor="$timecolor" --datecolor="$datecolor" \
#	--noinputtext=':O' --force-clock --timestr="%H:%M"
