#! /bin/sh

if [ $# = 0 ]
then
	page="$(apropos . | rofi -dmenu -i -font 'Roboto 12' -p manpdf -no-custom -scroll-method 1 -theme ~/.local/share/rofi/themes/slate.rasi | cut -d' ' -f1 )"
else
	page="$1"
fi

if [ "$page" != "" ] && [ "$(man -w "$page" 2>/dev/null)" != "" ]
then
	man -Tpdf "$page" | okular -
fi
