#! /bin/sh

if [ $# = 0 ]
then
	page="$(apropos -s 1 . | rofi -dmenu -i -p manpdf -no-custom -scroll-method 1 | cut -d' ' -f1 )"
else
	page="$1"
fi

if [ "$page" != "" ] && [ "$(man -w "$page" 2>/dev/null)" != "" ]
then
	man -Tpdf "$page" | okular -
fi
