#!/bin/bash
# script to edit ~/.config/mc.conf with currently running music player names

players="$(playerctl -l)"

if [[ "$1" == "-f" ]] && [[ "$(echo "$players" | wc -l )" -eq 1 ]]; then
  p="$players"
else
  p=$(echo "$players" | rofi -dmenu -p "choose player:" -no-custom)
fi

if [ "$p" != "" ]; then
	echo "$p" > ~/.config/mc.conf
fi
