#!/usr/bin/env bash
mu="$(\free -h --giga | awk '/^Mem/ {print $3}')"
if [[ "$1" == "bar" ]] ; then
  mu="$(\free | awk '/Mem/{ print $3 }')"
  mt="$(\free | awk '/Mem/{ print $2 }')"
  bar="$(vbar 0 "$mt" "$mu")"
  output="$bar"
else
  output="$mu"
fi

echo " $output"
