#!/bin/bash
# netspeed
# print the system's download and upload speed
# using /sys/class/net files
# stores a temporary file in HOME/.cache/netspeed
# uses formula SPEED = ( BYTES_NOW - BYTES_THEN (file) ) / TIME_DIFFERENCE
# this gives the average speed between this and last call
# to keep it close to instantaneous speed, keep call delta low (near to 1/sec)

# usage:
# netspeed [device name]
# device name - the name of the net adapter. Find yours using `ip link`
# ignore the lo (loopback device)
# if not providing device name on commandline arguments then make a file at
# HOME/.config/netspeed and store the device name in it
# example `echo "eth0" > ~/.config/netspeed" `


printspeed(){
  speed=$1 # in bytes per second
  # remove decimal
  speed=${speed%.*}
  speed=$((speed*8)) # convert to bits per second (bps)

  kb=$((1000)) # using decimal ( 1kb = 1000b)
  mb=$((kb*1000))
  gb=$((mb*1000))
  tb=$((gb*1000))

  if [[ $speed -ge $tb ]]; then
		printf "%2.0fT" "$((speed / tb))" # 1T = 1000G
	elif [[ $speed -ge $gb ]]; then
		printf "%2.0fG" "$((speed / gb))" # 1G = 1000M
	else
		printf "%2.0fM" "$((speed / mb))" # 1M = 1000K
	fi
}

TMPFILE="$HOME/.cache/netspeed"
CONFFILE="$HOME/.config/netspeed"

if test -n "$1"; then DEV="$1";
elif test -e "$CONFFILE" && test -n "$(cat "$CONFFILE")"; then
  DEV="$(cat "$CONFFILE")"
else
  echo "Either create a ${CONFFILE} with device name, or pass device name as arguments"
  echo "Maybe device name is $(netadn)"
  echo "Usage $( basename "$0") [device name]"
  exit 1
fi
RXFILE="/sys/class/net/$DEV/statistics/rx_bytes"
TXFILE="/sys/class/net/$DEV/statistics/tx_bytes"

if test -e "$TMPFILE" && test -n "$(cat "$TMPFILE")"; then
  TMPDATA="$(cat "$TMPFILE")"

  EPOCHOLD="$(echo "$TMPDATA" | cut -f 1)"
  RXOLD="$(echo "$TMPDATA" | cut -f 2)"
  TXOLD="$(echo "$TMPDATA" | cut -f 3)"

  EPOCHNEW="$(date +%s.%N)"
  RXNEW="$(cat "$RXFILE")"
  TXNEW="$(cat "$TXFILE")"


  EPOCHDIFF="$(bc <<< "$EPOCHNEW - $EPOCHOLD")" #seconds
  RXDIFF="$(bc <<< "$RXNEW - $RXOLD")" #bytes
  TXDIFF="$(bc <<< "$TXNEW - $TXOLD")" #bytes

  UPSPEED="$(bc <<< "$TXDIFF / $EPOCHDIFF")" #bps
  DOWNSPEED="$(bc <<< "$RXDIFF / $EPOCHDIFF")" #bps

  printf ""
  printspeed "$DOWNSPEED"
  printf " "
  printspeed "$UPSPEED"
  echo

  echo -e "$EPOCHNEW\t$RXNEW\t$TXNEW" > "$TMPFILE"
else
  EPOCHNEW="$(date +%s.%N)"
  RXNEW="$(cat "$RXFILE")"
  TXNEW="$(cat "$TXFILE")"
  echo -e "$EPOCHNEW\t$RXNEW\t$TXNEW" > "$TMPFILE"
  $0
fi
