#!/bin/bash

if test -z "$PACKLIST" ;then echo 'PACKLIST not defined' ; exit 1; fi
cd "$( dirname "$PACKLIST" )" || exit

# make temporary files to store current system state and backup pkglist
pkghere=$(mktemp pkgsyncXXXXXXX)
pkglist=$(mktemp pkgsyncXXXXXXX)
pkglist > "$pkghere"
cat "$(basename "$PACKLIST")" > "$pkglist"

# install any missing packages in this systems
inslist="$(diff "$pkghere" "$pkglist" | grep "^>" | cut -d' ' -f2 | tr '\n' ' ')"
if test -n "$inslist" ; then
  echo "Installing packages: $inslist"
  yay -S --needed $inslist
else
  echo "Nothing to install"
fi

# then remove extra packages present:
dellist="$(diff "$pkghere" "$pkglist"  | grep "^<" | cut -d' ' -f2 | tr '\n' ' ')"
if test -n "$dellist" ; then
  echo "Removing packages: $dellist"
  yay -Rns $dellist
else
  echo "Nothing to remove"
fi

# remove temporary files
rm "$pkglist"
rm "$pkghere"

