#!/bin/bash

if test -z "$PACKLIST" ;then
  if [[ -r $XDG_CONFIG_HOME/pkgsync/pkgsync.conf ]] ; then
    # shellcheck disable=1091
    source "$XDG_CONFIG_HOME"/pkgsync/pkgsync.conf
  fi
fi

if test -z "$PACKLIST" ;then echo 'PACKLIST not defined' ; exit 1; fi
cd "$( dirname "$PACKLIST" )" || exit


# install any missing packages in this systems
inslist="$(grep -xvf <(pkglist) "$(basename "$PACKLIST")" | tr '\n' ' ')"
if test -n "$inslist" ; then
  echo "Installing packages: $inslist"
  yay -S --noconfirm --needed $inslist
else
  echo "Nothing to install"
fi


