#!/bin/env bash

# Options for powermenu
lock="   Lock"
logout="󰗼   Logout"
shutdown="   Shutdown"
reboot="󰁯   Reboot"
sleep="  Sleep"

# Get answer from user via rofi
selected_option=$(echo "$lock
$logout
$sleep
$reboot
$shutdown" | rofi -dmenu\
                  -i\
                  -p "Power"\
                  -width "15"\
                  -lines 5\
                  -line-margin 3\
                  -line-padding 10\
                  -scrollbar-width "0" )

# Do something based on selected option
if [ "$selected_option" == "$lock" ]
then
    loginctl lock-session "${XDG_SESSION_ID-1}"
elif [ "$selected_option" == "$logout" ]
then
    killall dwm
elif [ "$selected_option" == "$shutdown" ]
then
    poweroff
elif [ "$selected_option" == "$reboot" ]
then
    reboot
elif [ "$selected_option" == "$sleep" ]
then
    amixer set Master mute
    systemctl suspend
else
    :
fi
