#!/bin/bash

# check if video0 is working or not
if videocheck &> /dev/null; then
	echo "v4l2loopback_dc is already installed"
	exit 0
fi

#remove older version
sudo /opt/droidcam-uninstall

#download latest version
cd /tmp/ || exit 1
sudo rm -rf droidcam_latest.zip
sudo rm -rf droidcam/
sudo wget https://www.dev47apps.com/files/linux/droidcam_latest.zip

#install
unzip droidcam_latest.zip -d droidcam && cd droidcam || exit 1
sudo ./install-client
sudo ./install-video
echo "done"
