#!/bin/bash

cache="$HOME/.cache/reincarnate"
while true; do
  rm "$cache"
  while read winid desktop pid host name ; do 
    echo -e "$name\t$(realpath "/proc/$pid/exe")" >> "$cache" 
  done < <(wmctrl -pl)
  sleep 1
done
