#!/bin/bash

temulator="konsole -e"
cd ~/scripts/ || exit 1
file="$(find -- * -executable -type f | rofi -dmenu -i -p scripts)"

if [ "$1" == "here" ]; then temulator=""; fi

if [ "$file" ]; then
	$temulator initscript "$file"
fi
