#!/usr/bin/env bash

if [ -z "$XDG_CONFIG_HOME" ]; then
  export XDG_CONFIG_HOME="$HOME/.config"
fi

if [ ! -f "$XDG_CONFIG_HOME"/servehost/domain ]; then
  echo "Please create a file at $XDG_CONFIG_HOME/servehost/domain with the domain you want to use"
  exit 1
fi

DOMAIN="$(cat "$XDG_CONFIG_HOME"/servehost/domain)"

http-server -c -1 -p 8080 &> /dev/null &
xsel -ib <<< "http://$DOMAIN"
ngrok http --domain="$DOMAIN" 8080
kill %1
