#!/bin/bash
freq=$1
dur=$2
if [ "$1" == "" ] || [ "$2" == "" ]
then
	echo -e "Usage:\nsine FREQUENCY DURATION"
	exit 0
fi
if [ "$2" == "0" ]
then
	dur="0.000001"
fi
ffplay -f lavfi -i "sine=frequency=${freq}:duration=${dur}" -nodisp -autoexit &> /dev/null
exit 0
