#!/bin/bash
# open favourite sites with browser through rofi menu
read -ra input < <(rofi -dmenu -i -scroll-method 1 -p ' open' <  ~/.config/sites.conf | cut -f2)

if [[ "${input[*]}" = "new" ]]; then
	konsole -e "$EDITOR" "$HOME/.config/sites.conf"
elif [[ -n "${input[*]}" ]]; then
	${BROWSER:-firefox} "${input[@]}"
fi
