#!/bin/bash
# open favourite sites with browser through rofi menu
input=$(rofi -theme ~/.local/share/rofi/themes/onedark.rasi -dmenu -i -scroll-method 1 -p ' open' <  ~/.config/sites.conf | cut -d'	' -f2)

if [[ -n "$input" ]] && [ "$input" != "new" ]
then
	${BROWSER:-chromium} $input
elif [ "$input" = "new" ]
then
	konsole -e vim $HOME/.config/sites.conf
fi
