#!/usr/bin/env bash
shopt -s nullglob
# Check subcommand
if [ "${1}" == 'type' ] || [ "${1}" == 'copy' ]; then
  subcommand="${1}"
else
  echo "Usage: $(basename "$0") [copy|type] [DATAFILES*]"
  echo "Quickly look up and input emoji and/or emoticons/kaomoji" \
    "on your GNU/Linux desktop via pop-up menu."
  exit 1
fi
shift

# Determine config files
if [ -f "${XDG_CONFIG_HOME:-${HOME}/.config}/splatmoji/splatmoji.config" ]; then
  conffile="${XDG_CONFIG_HOME:-${HOME}/.config}/splatmoji/splatmoji.config"
fi

datafiles_list=()

# Read command line data files
if [ $# -ne 0 ]; then
  datafiles_list=("${@:1}")
fi

USER_DF="${XDG_DATA_HOME:-${HOME}/.local/share}/splatmoji/data"
# Read per-user data files
if [ -d "${USER_DF}" ]; then
  mapfile -O ${#datafiles_list[@]} -t datafiles < <(find "${USER_DF}" -mindepth 1 -maxdepth 1 -type f | sort )
  datafiles_list+=("${datafiles[@]}")
fi

# Read config
declare -A config
while IFS='' read -r line; do
  if [[ -z "${line}" ]] || [ "${line:0:1}" == '#' ]; then
    continue
  fi
  key="${line%%=*}"
  val="${line#*=}"
  config["${key}"]="${val}"
done < "${conffile}"

# Prompt user for selection
selection=$(cat "${datafiles_list[@]}" | eval "${config[rofi_command]}")
moji="${selection%%$'\t'*}"

if [ -z "$moji" ]; then exit; fi
# Results to clipboard or selected x window
if [ "${subcommand}" == 'type' ]; then
  ${config[xdotool_command]} "${moji}"
fi
echo -n "${moji}" | ${config[xsel_command]}
