#!/bin/bash


if [ ! -e ~/.cache/spotify-now-playing ] 
then
	spotify-song > ~/.cache/spotify-now-playing
	exit 0
fi

prev="$(cat ~/.cache/spotify-now-playing)"
current="$(~/scripts/spotify-song)"

if [ "$prev" != "$current" ]
then
	notify-send -a "Spotify" "$current" -h string:desktop-entry:spotify
fi
echo "$current" > ~/.cache/spotify-now-playing
echo " "
