#!/bin/bash

running=1

dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata 2>&1 | grep -v Error >/dev/null || running=0

if [ $running == 0 ]
then
#	echo Spotify not running
	exit 0
fi

title=$(dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata | grep "title" -A1 | grep "variant" | cut -d'"' -f2)

artist=$(dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata | grep "artist" -A2 | grep "\"" | grep -v "xesam" | cut -d'"' -f2)

echo "$artist - $title"
