#!/bin/bash
# relaunch DWM if the binary changes, otherwise bail
conf="$HOME/.config/startdwm"

~/.xprofile &
# ~/.local/share/dwm/autostart.sh &
[ -e ~/.fehbg ] && ~/.fehbg &

csum=""
new_csum=$(sha1sum "$(which dwm)")
while true
do
    if [ "$csum" != "$new_csum" ]
    then
        csum=$new_csum
        dwm
	elif [ -r "$conf" ] && grep -q "restart" "$conf"; then
		dwm
	else
        exit 0
    fi
    new_csum=$(sha1sum "$(which dwm)")
    sleep 0.1
done
