#!/bin/bash
# relaunch DWM if the binary changes, otherwise bail

NOTICENTER="dunst"
COMPOSITOR="picom"
killall $NOTICENTER
$NOTICENTER &

killall $COMPOSITOR
$COMPOSITOR &

~/.xprofile
[ -e ~/.fehbg ] && ~/.fehbg &

csum=""
new_csum=$(sha1sum $(which dwm))
while true
do
    if [ "$csum" != "$new_csum" ]
    then
        csum=$new_csum
        dwm
    else
        exit 0
    fi
    new_csum=$(sha1sum $(which dwm))
    sleep 0.5
done
