#!/bin/bash
prev=$(xbacklight -get)
reset() {
	xbacklight -set "$prev"
}
trap "reset" EXIT
trap "exit 0" TERM INT
while true; do 
		xbacklight -steps 100 -set 0 &> /dev/null
		xbacklight -steps 100 -set 100 &> /dev/null
done
