#!/bin/bash
# create a new file from a template file.
# works using the file extension.
# looks for the template file with same extension in
# templates folder and copies it to the cwd with the passed name

# usage: 
# tmpl tree.cpp
# tmpl reversal.cp.cpp
# tmpl sortQ.java

# this script will replace initc initcpp initjava etc into one script

if test "$#" -lt 1 ; then
	echo "usage: $(basename "$0") filename.ext"
	exit 1
fi

extension=$(echo "$1" | cut -d '.' -f2-)
TMPDIR="${HOME}/docs/libraries/templates"

if ! test -r "${TMPDIR}/template.${extension}"; then
	echo "$extension template not present in ${TMPDIR}"
	exit 1
fi

if ! test -e "${1}"; then
	cp "${TMPDIR}/template.${extension}" "./${1}"
fi

if test -z "$EDITOR" ; then EDITOR=vi; fi
"$EDITOR" "${1}"
