#!/bin/bash

if [ ! "$1" ]
then
	 echo "Pass Keycode!"
	 exit 1
fi
adb shell input keyevent 82 # send menu click (turn on screen)
adb shell input keyevent 82 # send menu click (swipe up)
adb shell input text "$1"   # type passcode (taken as command line parameter)
adb shell input keyevent 66 # send enter key
