#!/usr/bin/env bash

adb shell input keyevent 82 # send menu click (turn on screen)

if [ "$1" ]
then
  adb shell input keyevent 82 # send menu click (swipe up)
  adb shell input text "$1"   # type passcode (taken as command line parameter)
  adb shell input keyevent 66 # send enter key
fi
