#!/usr/bin/env bash

# To be run as a pacman hook, so PACKLIST should be defined in /etc/environment
# and a hook file to be created and put in /etc/pacman.d/hooks/
# Example hooks file:

#[Trigger]
#Operation = Install
#Operation = Upgrade
#Operation = Remove
#Type = Package
#Target = *
#
#[Action]
#Description = Update the package list
#Exec = /home/sayan/scripts/updatepkglist
#When = PostTransaction
#Depends = coreutils
#Depends = pacman



pkglist > "${PACKLIST}"

# once generated, use pkgsync to install any missing packages in others systems
# and remove extra packages present
