#!/bin/bash

# To be run as a pacman hook, so PACKLIST should be defined in /etc/environment
# and a hook file to be created and put in /etc/pacman.d/hooks/
# Example hooks file:

#[Trigger]
#Operation = Install
#Operation = Upgrade
#Operation = Remove
#Type = Package
#Target = *
#
#[Action]
#Description = Update the package list
#Exec = /home/sayan/scripts/updatepkglist
#When = PostTransaction
#Depends = coreutils
#Depends = pacman



pkglist > ${PACKLIST}

# once generated, use the pkglist to install any missing packages in others systems
# using the command:
# pkglist > pkghere
# yay -S --needed $(diff pkghere pkglist | grep '^>' | cut -d' ' -f2 | tr '\n' ' ')

# then remove extra packages present using:
# pkglist > pkghere
# yay -Rns $(diff pkghere pkglist  | grep "^<" | cut -d' ' -f2 | tr '\n' ' ')
