#!/bin/bash
# one command to set, increase, decrease, mute, and 
# display sink volume

## usage:
## vol           -> displays the current volume
## vol up/down   -> increase/decrease volume by 5%
## vol 52%       -> set the volume to 52%
## vol +17%      -> increase the volume by 17%
## vol -14%      -> decrease the volume by 14%
## vol mute      -> toggle volume mute (turns mute on/off)
cmd="volume"
if [ -n "$1" ]
then
	case $1 in
		up) val="+5%";;
		down) val="-5%";;
		mute) cmd="mute"; val="toggle";;
		*) val=$1;;
	esac
	sink=$(pactl list sinks | grep -oP 'Sink #\K([0-9]+)')
	pactl -- set-sink-"$cmd" "$sink" "$val"
fi
# display volume
ps=$(amixer get Master | tail -n1)
vol=$(echo "$ps" | grep -Po ".*\[\K\d*%")
mute=$(echo "$ps" | grep -Po ".*\[\K\w*")
case $mute in
	on) echo " $vol";;
	*)  echo "🔇";;
esac
