#!/bin/bash
# one command to set, increase, decrease, mute, and
# display sink volume

## usage:
## vol           -> displays the current volume
## vol up/down   -> increase/decrease volume by 5%
## vol 52%       -> set the volume to 52%
## vol +17%      -> increase the volume by 17%
## vol -14%      -> decrease the volume by 14%
## vol mute      -> toggle volume mute (turns mute on/off)
cmd="volume"
step="5"
if [[ -n "$1" ]]
then
	case $1 in
		up) val="+${step}%";;
		down) val="-${step}%";;
		mute) cmd="mute"; val="toggle";;
		bar) val="+0%" ;;
		*) val=$1;;
	esac
	pactl -- set-sink-"$cmd" "@DEFAULT_SINK@" "$val"
fi
# display volume
ps=$(amixer get Master | tail -n1)
vol=$(pactl -- get-sink-volume "@DEFAULT_SINK@" | grep -oP '\d*%' | uniq)
mute=$(echo "$ps" | grep -Po ".*\[\K\w*")
# show the volume bar using ascii characters
display_steps=10
bar=""
for i in $(seq 0 $((100 / display_steps)) 100) ; do
  # compare the vol with i after removing the % from end of vol
  if [[ "${vol//%/}" -ge "$i" ]]; then
    bar="${bar}#"
  else
    bar="${bar}-"
  fi
done
if [[ ${vol//%/} -gt 100 ]]; then
  bar="${bar}+"
fi
output="$vol"
if [[ "$1" == "bar" ]]; then
  output="$bar"
fi
case $mute in
	on) echo " $output";;
	*)  echo "🔇";;
esac
