#!/bin/bash
get(){
	info=$(curl -sf wttr.in/?format=%c%t)
	echo "$info" > ~/.cache/weatherinfo
}

if [ ! -e ~/.cache/weatherinfo ] || [ "$(grep -c '°C' ~/.cache/weatherinfo )" = 0 ] 
then
	get
fi

date1=$(date +%H)
date2=$(date -r ~/.cache/weatherinfo +%H)

if [ "$date1" != "$date2" ]
then
	get
fi

resp=$(cat ~/.cache/weatherinfo)

echo "$resp" | tr '+' ' '
