#!/bin/bash
get(){
	info=$(curl -sf wttr.in/?format=%c%t)
	if [ "$(echo "$info" | grep -c '°C' )" = 0 ]
	then
		return
	else
		echo "$info" > ~/.cache/weatherinfo
	fi
}

if [ ! -e ~/.cache/weatherinfo ] || [ "$(grep -c '°C' ~/.cache/weatherinfo )" = 0 ] 
then
	get &
	exit 0
fi

date1=$(date +%H)
date2=$(date -r ~/.cache/weatherinfo +%H)

if [ "$date1" != "$date2" ]
then
	get &
	exit 0
fi

resp=$(cat ~/.cache/weatherinfo)

echo "$resp" | tr -d '+' 
