#!/bin/bash
# search videos on youtube and play them in mpv, without an API key
# Sayan G

if [ "$1" == "" ]; then 
	echo -n "Search: "
	read query
else
	query="$@"
fi
if [ "$query" == "" ]; then exit; fi 
query=$(sed 's| |+|g' <<< $query)	
videoid=$(
curl -s https://www.youtube.com/results?search_query=$query | \
	grep -oP "\"videoRenderer\":{\"videoId\":\"...........\".+?\"text\":\".+?(?=\")" | \
	awk -F\" '{ print $6 " " $NF}' | \
	fzf --with-nth='2..-1' | \
	cut -d' ' -f1)
if [ "$videoid" == "" ]; then exit; fi	
mpv https://youtu.be/$videoid	
