#!/usr/bin/env bash

# extract a youtube thumbnail from link using yt-dlp

# get the link
if [[ $# -ge 1 ]]; then
link="$1"
else
  read -rp "Enter the youtube link: " link
fi



# get the thumbnail
thumbnail="$(yt-dlp --get-thumbnail "$link")"

if [[ -z "$thumbnail" ]]; then
    echo "no thumbnail found"
    exit 1
fi

#extract id from link
id="$(grep -oE '[a-zA-Z0-9_-]{11}' <<< "$thumbnail" | head -1)"

# get the extension
ext="${thumbnail##*.}"

filename="${id}.${ext}"

echo "$thumbnail"
echo "download? [Y/n]"
read -r download

# download the thumbnail if requested
if [[ "$download" != "n" ]]; then
    echo "downloading into $filename"
    wget "$thumbnail" --quiet -O "$filename" || exit 1
fi

